PRAGMA foreign_keys = ON;

-- AGENTE
INSERT INTO Agente (id,nome,telemovel,email) VALUES (1,"Sydney Guerrero",879746739965,"blandit@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (2,"Martena Burks",854240777896,"dolor@gmail.comt");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (3,"Sara Pugh",306109151659,"magnaipsum@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (4,"Georgia Reyes",248199719886,"dui@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (5,"Evangeline Hart",231755238171,"magnisurient@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (6,"Cassidy Buckner",151708193432,"ridiculus@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (7,"Merrill Carlson",454926889826,"luctus@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (8,"Nissim Kirby",461541280977,"nunc@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (9,"Kirk Craig",674720110737,"necada@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (10,"Brynne Good",397245272386,"placerati@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (11,"Rhoda Kirk",129513894754,"velarcu@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (12,"Howard Horne",249662910608,"feugiat@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (13,"Fay Becker",909261545712,"semollis@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (14,"Brian Fields",768537696787,"eupodio@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (15,"Addison Velazquez",267679162708,"ettique@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (16,"Cleo Gordon",719573882236,"volupalla@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (17,"Brendan Petty",577861305801,"Nulla@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (18,"Macaulay Garrison",952729727918,"Proinquam@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (19,"Rhonda Phillips",502743114347,"convallis@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (20,"Fay Ferguson",936706868514,"tincidunt@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (21,"Yetta Rowe",185715760399,"Suspendisse@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (22,"Fletcher Caldwell",766109504662,"puisque@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (23,"Leilani Buckley",978153945936,"disarturient@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (24,"Orli Fisher",303804726291,"maurisut@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (25,"Brock Levy",200155404602,"pellentesque@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (26,"Aphrodite Cooley",644214722492,"ererit@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (27,"Justin Bond",261552556477,"lauisque@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (28,"Lesley Rodriquez",580115601415,"fringilla@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (29,"Malcolm Young",609546122664,"nibh54@gmail.com");
INSERT INTO Agente (id,nome,telemovel,email) VALUES (30,"Phillip Gardner",889644154678,"tellus@gmail.com");

-- GENERO
INSERT INTO Genero (id,nome) VALUES (1,"Rock");
INSERT INTO Genero (id,nome) VALUES (2,"Heavy Metal");
INSERT INTO Genero (id,nome) VALUES (3,"Classical");
INSERT INTO Genero (id,nome) VALUES (4,"Hip Hop");
INSERT INTO Genero (id,nome) VALUES (5,"Eletronic Punk");
INSERT INTO Genero (id,nome) VALUES (6,"Jazz");
INSERT INTO Genero (id,nome) VALUES (7,"Country");
INSERT INTO Genero (id,nome) VALUES (8,"Dubstep");
INSERT INTO Genero (id,nome) VALUES (9,"Reggae");
INSERT INTO Genero (id,nome) VALUES (10,"Blues");
INSERT INTO Genero (id,nome) VALUES (11,"Techno");
INSERT INTO Genero (id,nome) VALUES (12,"EDM");
INSERT INTO Genero (id,nome) VALUES (13,"Pop");
INSERT INTO Genero (id,nome) VALUES (14,"Disco");
INSERT INTO Genero (id,nome) VALUES (15,"Soul");
INSERT INTO Genero (id,nome) VALUES (16,"K-pop");
INSERT INTO Genero (id,nome) VALUES (17,"Ambient");
INSERT INTO Genero (id,nome) VALUES (18,"RAP");
INSERT INTO Genero (id,nome) VALUES (19,"Indie");
INSERT INTO Genero (id,nome) VALUES (20,"Funk");

-- CLASSIFICACAO
INSERT INTO Classificacao (id,tipo) VALUES (1,"Food");
INSERT INTO Classificacao (id,tipo) VALUES (2,"Lounge");
INSERT INTO Classificacao (id,tipo) VALUES (3,"Photography");
INSERT INTO Classificacao (id,tipo) VALUES (4,"Games");
INSERT INTO Classificacao (id,tipo) VALUES (5,"Informative");
INSERT INTO Classificacao (id,tipo) VALUES (6,"Deposit");
INSERT INTO Classificacao (id,tipo) VALUES (7,"Exchange");
INSERT INTO Classificacao (id,tipo) VALUES (8,"Charging");

-- TIPO
INSERT INTO Tipo (id,nome) VALUES (1,"Representante");
INSERT INTO Tipo (id,nome) VALUES (2,"Media");
INSERT INTO Tipo (id,nome) VALUES (3,"Celebridade");
INSERT INTO Tipo (id,nome) VALUES (4,"Outro");

-- NACIONALIDADE
INSERT INTO Nacionalidade (id,nome) VALUES (1,"New Zealand");
INSERT INTO Nacionalidade (id,nome) VALUES (2,"Dubai");
INSERT INTO Nacionalidade (id,nome) VALUES (3,"Uzbekistan");
INSERT INTO Nacionalidade (id,nome) VALUES (4,"South Korea");
INSERT INTO Nacionalidade (id,nome) VALUES (5,"Timor-Leste");
INSERT INTO Nacionalidade (id,nome) VALUES (6,"Algeria");
INSERT INTO Nacionalidade (id,nome) VALUES (7,"Pakistan");
INSERT INTO Nacionalidade (id,nome) VALUES (8,"Kazakhstan");
INSERT INTO Nacionalidade (id,nome) VALUES (9,"China");
INSERT INTO Nacionalidade (id,nome) VALUES (10,"Portugal");
INSERT INTO Nacionalidade (id,nome) VALUES (11,"India");
INSERT INTO Nacionalidade (id,nome) VALUES (12,"Venezuela");
INSERT INTO Nacionalidade (id,nome) VALUES (13,"Thailand");
INSERT INTO Nacionalidade (id,nome) VALUES (14,"Australia");
INSERT INTO Nacionalidade (id,nome) VALUES (15,"Germany");
INSERT INTO Nacionalidade (id,nome) VALUES (16,"Canada");
INSERT INTO Nacionalidade (id,nome) VALUES (17,"Albania");
INSERT INTO Nacionalidade (id,nome) VALUES (18,"Malta");
INSERT INTO Nacionalidade (id,nome) VALUES (19,"Mali");
INSERT INTO Nacionalidade (id,nome) VALUES (20,"Nigeria");
INSERT INTO Nacionalidade (id,nome) VALUES (21,"Hungary");
INSERT INTO Nacionalidade (id,nome) VALUES (22,"Japan");
INSERT INTO Nacionalidade (id,nome) VALUES (23,"Spain");
INSERT INTO Nacionalidade (id,nome) VALUES (24,"Poland");
INSERT INTO Nacionalidade (id,nome) VALUES (25,"Angola");
INSERT INTO Nacionalidade (id,nome) VALUES (26,"Mozambique");
INSERT INTO Nacionalidade (id,nome) VALUES (27,"Greenland");
INSERT INTO Nacionalidade (id,nome) VALUES (28,"Denmark");
INSERT INTO Nacionalidade (id,nome) VALUES (29,"USA");
INSERT INTO Nacionalidade (id,nome) VALUES (30,"Brazil");
INSERT INTO Nacionalidade (id,nome) VALUES (31,"Italy");
INSERT INTO Nacionalidade (id,nome) VALUES (32,"United Kingdom");
INSERT INTO Nacionalidade (id,nome) VALUES (33,"South Africa");
INSERT INTO Nacionalidade (id,nome) VALUES (34,"Gambia");
INSERT INTO Nacionalidade (id,nome) VALUES (35,"France");
INSERT INTO Nacionalidade (id,nome) VALUES (36,"Ireland");
INSERT INTO Nacionalidade (id,nome) VALUES (37,"Macao");
INSERT INTO Nacionalidade (id,nome) VALUES (38,"Argentina");
INSERT INTO Nacionalidade (id,nome) VALUES (39,"Turkmenistan");
INSERT INTO Nacionalidade (id,nome) VALUES (40,"Namibia");
INSERT INTO Nacionalidade (id,nome) VALUES (41,"Montenegro");
INSERT INTO Nacionalidade (id,nome) VALUES (42,"Liberia");
INSERT INTO Nacionalidade (id,nome) VALUES (43,"Niger");
INSERT INTO Nacionalidade (id,nome) VALUES (44,"Norway");
INSERT INTO Nacionalidade (id,nome) VALUES (45,"Mexico");
INSERT INTO Nacionalidade (id,nome) VALUES (46,"Yemen");
INSERT INTO Nacionalidade (id,nome) VALUES (47,"Greece");
INSERT INTO Nacionalidade (id,nome) VALUES (48,"Kenya");
INSERT INTO Nacionalidade (id,nome) VALUES (49,"Russia");
INSERT INTO Nacionalidade (id,nome) VALUES (50,"Sweden");

-- ENTIDADE
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (1,"Vodafone",879723439965,"vodafone_inc@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (2,"Santander",854670777896,"santander@gmail.comt");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (3,"Sagres",306109761659,"sagres@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (4,"EDP",248199713336,"edp@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (5,"Fnac",231754228171,"fnac@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (6,"Trident",156708893432,"trident@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (7,"Gant",454923884426,"gant@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (8,"Expresso",441541680977,"expresso_news@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (9,"Control",674720145737,"control@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (10,"Casablanca",397245272386,"casablanca_restaurant@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (11,"Rodizio Fontes",345138444754,"fontes_rod@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (12,"Bonsai Sushi",242762910608,"bonsai_shi@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (13,"Marklen",909261523712,"pr_marklen@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (14,"Hamburgology",762237693787,"hamburgology@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (15,"Vegan Bar",267672162238,"vegan_bar@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (16,"Gordon's Pizzas",713579232236,"gordonpizza@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (17,"Blends",577861305831,"blends_pr@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (18,"The Cru",952729772218,"Cru@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (19,"Starfish",502742117847,"starfishresources@gmail.com");
INSERT INTO Entidade (id,nome,telemovel,email) VALUES (20,"Plantification",932368958514,"plantf@gmail.com");

-- ARTISTA
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (1,"Fiona Miles",111446,1,14,50);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (2,"Odessa Valentine",44542,2,13,20);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (3,"George Orr",91501,3,14,40);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (4,"Jasmine Reeves",33669,4,8,45);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (5,"Adam Lester",146074,5,13,26);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (6,"Madeson Hogan",15776,6,8,14);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (7,"Violet Baird",158678,7,18,17);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (8,"Quamar Cline",63168,8,4,12);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (9,"Courtney Carson",29723,9,5,15);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (10,"Chase Dotson",12603,10,4,35);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (11,"Nyssa Wong",157851,11,19,21);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (12,"Mary Mcclain",186857,12,9,8);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (13,"Nissim Spencer",101286,13,19,6);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (14,"Baker Knight",128925,14,2,14);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (15,"Chastity Boyle",14485,15,17,37);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (16,"Slade Kirk",91577,16,20,36);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (17,"Allistair Adams",98203,17,6,42);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (18,"Driscoll Hendrix",162198,18,14,38);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (19,"Tyrone Baxter",98789,19,16,32);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (20,"Scott Mcdonald",193585,20,19,11);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (21,"Bradley Taylor",156169,21,8,43);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (22,"Hector Callahan",42559,22,9,30);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (23,"Asher Houston",18864,23,20,7);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (24,"Nina Cooper",36589,24,8,9);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (25,"Kibo Frost",67557,25,8,45);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (26,"Kadeem Freeman",69133,26,6,23);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (27,"Linda Morrison",152514,27,11,30);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (28,"Kevyn Rosario",62525,28,8,50);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (29,"Tanner Hunter",169061,29,8,42);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (30,"Lamar Kennedy",195647,30,14,43);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (31,"Orlando Mann",11107,23,5,8);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (32,"Grady Hudson",97881,2,4,27);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (33,"Gage Anderson",24545,15,17,48);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (34,"Shay Pittman",161428,21,13,27);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (35,"Amaya Beasley",115155,5,8,7);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (36,"Michael Craft",140433,16,10,6);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (37,"Colette Nichols",39328,27,11,22);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (38,"Glenna Farmer",126525,8,2,40);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (39,"Ronan Murphy",156618,29,18,14);
INSERT INTO Artista (id,nome,salario,agente,genero,nacionalidade) VALUES (40,"Kenneth Conway",81409,4,5,16);

-- PARTICIPANTE
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (1,"Camilla Bond",841210051,34);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (2,"Hollee Davenport",832877726,48);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (3,"Stacey Kinney",628959919,26);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (4,"Steven Acevedo",330397186,34);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (5,"Ryan Singleton",723119527,19);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (6,"Nasim Massey",424388669,8);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (7,"Axel Fulton",519792647,30);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (8,"Victoria Peters",416927972,11);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (9,"Mason Munoz",214306677,23);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (10,"Orlando Pena",586062056,43);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (11,"Rana Holloway",980723660,8);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (12,"Chase Monroe",347922822,17);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (13,"Halla Hess",886189651,34);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (14,"Cathleen Jensen",821097887,39);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (15,"Flavia Sharp",299312683,24);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (16,"Nigel Kirkland",714279194,27);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (17,"Ruth Fulton",616221165,19);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (18,"Astra Nash",443328997,36);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (19,"Naomi Pittman",670928287,19);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (20,"Evelyn Haney",261024032,33);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (21,"Beau Cherry",605468867,36);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (22,"Inga Potter",863109888,42);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (23,"Damian Odonnell",405927737,10);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (24,"Catherine Bell",175774683,8);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (25,"Beverly Baker",527113580,41);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (26,"Finn May",260843317,14);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (27,"Myles Clay",152384939,46);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (28,"Lillian Payne",543689939,6);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (29,"MacKenzie Reynolds",847779713,50);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (30,"Imani Murphy",412825571,10);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (31,"Drew Kelley",522484894,2);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (32,"Quinn Conrad",721549896,48);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (33,"Kuame Holder",964557177,18);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (34,"Camden Joyner",839735829,24);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (35,"Darryl Reed",863756986,31);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (36,"Autumn Robinson",593147615,5);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (37,"Jamalia Flores",883829207,7);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (38,"Tate Steele",387774090,32);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (39,"Harper Hampton",714741494,28);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (40,"Emerald Preston",268812192,5);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (41,"Drew Gould",940252857,6);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (42,"Nicole Pope",384168966,14);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (43,"Forrest Owen",126298824,26);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (44,"Rowan Lindsay",304649813,37);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (45,"Melissa Barrett",310969823,11);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (46,"Maggy Townsend",979913242,9);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (47,"Donovan Donovan",707977038,50);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (48,"Heidi Kim",461003199,33);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (49,"TaShya Schneider",423269871,15);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (50,"MacKensie Mcmahon",384121901,29);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (51,"Belle Fleming",288943281,2);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (52,"Fallon Lewis",665973512,16);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (53,"Lucas Bartlett",796814849,17);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (54,"Haley Brooks",220144972,3);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (55,"Brock Frederick",333156027,5);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (56,"Felix Whitaker",378819637,12);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (57,"Troy Kramer",282345281,37);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (58,"Hyatt Kemp",130547612,20);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (59,"Brenden Johns",439873676,6);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (60,"Melodie Cherry",170803339,21);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (61,"Ayanna Robles",296633523,6);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (62,"Uriel Kennedy",942547295,30);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (63,"Arthur Butler",916500067,40);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (64,"Castor Ayala",897624820,9);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (65,"Claudia Hinton",611724757,35);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (66,"Isadora Kelley",866774831,33);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (67,"Meredith Zamora",555575180,3);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (68,"Iliana Richards",217654164,38);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (69,"Eugenia Mcintyre",643613960,16);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (70,"Dante Rowland",793862539,2);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (71,"Lamar Bonner",868395460,12);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (72,"Quinn Coffey",562408670,12);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (73,"Halla May",102770887,18);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (74,"Philip Dudley",275801746,7);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (75,"Nehru Robbins",584717281,2);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (76,"Camille Glenn",242854232,10);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (77,"Martina Mooney",213079067,2);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (78,"Grace Wagner",515937543,39);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (79,"Keaton Johns",188679443,37);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (80,"Randall English",285998304,36);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (81,"Ava Miles",450147098,17);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (82,"Uriah Rose",837296305,37);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (83,"Walter Alvarado",759142434,43);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (84,"Sydney Hardin",602030526,44);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (85,"Chiquita Rush",437071058,44);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (86,"Unity Erickson",124793091,6);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (87,"Kieran Burt",202769379,26);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (88,"Zahir Snyder",512728197,1);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (89,"Talon Osborne",801432113,44);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (90,"Darius Hayden",264954367,48);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (91,"Germaine Larsen",850621880,4);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (92,"Keefe Pierce",848463068,12);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (93,"Ursa Cleveland",739820988,15);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (94,"Sawyer Crane",242888206,48);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (95,"Zahir Newton",221659411,4);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (96,"Joshua Cantrell",213673506,7);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (97,"Reed Langley",152724672,25);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (98,"Britanni Leblanc",956945014,38);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (99,"Brynn Franklin",537257570,8);
INSERT INTO Participante (id,nome,nif,nacionalidade) VALUES (100,"Xenos Carrillo",157762952,27);

-- NORMAL
INSERT INTO Normal (participante,menor_idade) VALUES (53,0);
INSERT INTO Normal (participante,menor_idade) VALUES (72,0);
INSERT INTO Normal (participante,menor_idade) VALUES (77,0);
INSERT INTO Normal (participante,menor_idade) VALUES (34,0);
INSERT INTO Normal (participante,menor_idade) VALUES (79,1);
INSERT INTO Normal (participante,menor_idade) VALUES (69,0);
INSERT INTO Normal (participante,menor_idade) VALUES (71,0);
INSERT INTO Normal (participante,menor_idade) VALUES (27,0);
INSERT INTO Normal (participante,menor_idade) VALUES (32,0);
INSERT INTO Normal (participante,menor_idade) VALUES (44,0);
INSERT INTO Normal (participante,menor_idade) VALUES (24,0);
INSERT INTO Normal (participante,menor_idade) VALUES (76,0);
INSERT INTO Normal (participante,menor_idade) VALUES (74,0);
INSERT INTO Normal (participante,menor_idade) VALUES (19,0);
INSERT INTO Normal (participante,menor_idade) VALUES (40,0);
INSERT INTO Normal (participante,menor_idade) VALUES (11,0);
INSERT INTO Normal (participante,menor_idade) VALUES (12,1);
INSERT INTO Normal (participante,menor_idade) VALUES (4,0);
INSERT INTO Normal (participante,menor_idade) VALUES (25,0);
INSERT INTO Normal (participante,menor_idade) VALUES (2,0);
INSERT INTO Normal (participante,menor_idade) VALUES (31,0);
INSERT INTO Normal (participante,menor_idade) VALUES (55,0);
INSERT INTO Normal (participante,menor_idade) VALUES (42,0);
INSERT INTO Normal (participante,menor_idade) VALUES (65,0);
INSERT INTO Normal (participante,menor_idade) VALUES (33,0);
INSERT INTO Normal (participante,menor_idade) VALUES (20,0);
INSERT INTO Normal (participante,menor_idade) VALUES (13,0);
INSERT INTO Normal (participante,menor_idade) VALUES (50,1);
INSERT INTO Normal (participante,menor_idade) VALUES (37,0);
INSERT INTO Normal (participante,menor_idade) VALUES (41,0);
INSERT INTO Normal (participante,menor_idade) VALUES (67,0);
INSERT INTO Normal (participante,menor_idade) VALUES (39,1);
INSERT INTO Normal (participante,menor_idade) VALUES (75,0);
INSERT INTO Normal (participante,menor_idade) VALUES (21,0);
INSERT INTO Normal (participante,menor_idade) VALUES (30,0);
INSERT INTO Normal (participante,menor_idade) VALUES (64,0);
INSERT INTO Normal (participante,menor_idade) VALUES (61,0);
INSERT INTO Normal (participante,menor_idade) VALUES (17,0);
INSERT INTO Normal (participante,menor_idade) VALUES (15,0);
INSERT INTO Normal (participante,menor_idade) VALUES (45,0);
INSERT INTO Normal (participante,menor_idade) VALUES (54,0);
INSERT INTO Normal (participante,menor_idade) VALUES (70,0);
INSERT INTO Normal (participante,menor_idade) VALUES (59,0);
INSERT INTO Normal (participante,menor_idade) VALUES (63,0);
INSERT INTO Normal (participante,menor_idade) VALUES (52,0);
INSERT INTO Normal (participante,menor_idade) VALUES (47,0);
INSERT INTO Normal (participante,menor_idade) VALUES (23,0);
INSERT INTO Normal (participante,menor_idade) VALUES (57,1);
INSERT INTO Normal (participante,menor_idade) VALUES (1,0);
INSERT INTO Normal (participante,menor_idade) VALUES (6,0);
INSERT INTO Normal (participante,menor_idade) VALUES (9,0);
INSERT INTO Normal (participante,menor_idade) VALUES (78,0);
INSERT INTO Normal (participante,menor_idade) VALUES (60,0);
INSERT INTO Normal (participante,menor_idade) VALUES (8,0);
INSERT INTO Normal (participante,menor_idade) VALUES (14,1);
INSERT INTO Normal (participante,menor_idade) VALUES (49,0);
INSERT INTO Normal (participante,menor_idade) VALUES (18,0);
INSERT INTO Normal (participante,menor_idade) VALUES (28,0);
INSERT INTO Normal (participante,menor_idade) VALUES (66,0);
INSERT INTO Normal (participante,menor_idade) VALUES (7,0);
INSERT INTO Normal (participante,menor_idade) VALUES (56,0);
INSERT INTO Normal (participante,menor_idade) VALUES (16,1);
INSERT INTO Normal (participante,menor_idade) VALUES (22,0);
INSERT INTO Normal (participante,menor_idade) VALUES (68,0);
INSERT INTO Normal (participante,menor_idade) VALUES (80,0);
INSERT INTO Normal (participante,menor_idade) VALUES (36,0);
INSERT INTO Normal (participante,menor_idade) VALUES (58,0);
INSERT INTO Normal (participante,menor_idade) VALUES (3,0);
INSERT INTO Normal (participante,menor_idade) VALUES (46,0);
INSERT INTO Normal (participante,menor_idade) VALUES (10,0);
INSERT INTO Normal (participante,menor_idade) VALUES (26,0);
INSERT INTO Normal (participante,menor_idade) VALUES (62,0);
INSERT INTO Normal (participante,menor_idade) VALUES (38,0);
INSERT INTO Normal (participante,menor_idade) VALUES (5,0);
INSERT INTO Normal (participante,menor_idade) VALUES (43,1);
INSERT INTO Normal (participante,menor_idade) VALUES (51,0);
INSERT INTO Normal (participante,menor_idade) VALUES (48,0);
INSERT INTO Normal (participante,menor_idade) VALUES (35,0);
INSERT INTO Normal (participante,menor_idade) VALUES (73,0);
INSERT INTO Normal (participante,menor_idade) VALUES (29,1);

-- ACOMPANHA
INSERT INTO Acompanha (menor,adulto) VALUES (79,16);
INSERT INTO Acompanha (menor,adulto) VALUES (12,27);
INSERT INTO Acompanha (menor,adulto) VALUES (50,41);
INSERT INTO Acompanha (menor,adulto) VALUES (39,48);
INSERT INTO Acompanha (menor,adulto) VALUES (57,44);
INSERT INTO Acompanha (menor,adulto) VALUES (14,78);
INSERT INTO Acompanha (menor,adulto) VALUES (16,20);
INSERT INTO Acompanha (menor,adulto) VALUES (43,44);
INSERT INTO Acompanha (menor,adulto) VALUES (29,79);

-- TIPOBILHETE
INSERT INTO TipoBilhete (id,nome,data_inicio,data_fim,acampamento,custo) VALUES (1,"Diario","09/07/2019","09/07/2019",0,"60");
INSERT INTO TipoBilhete (id,nome,data_inicio,data_fim,acampamento,custo) VALUES (2,"Diario","09/07/2019","09/07/2019",1,"80");
INSERT INTO TipoBilhete (id,nome,data_inicio,data_fim,acampamento,custo) VALUES (3,"Diario","10/07/2019","10/07/2019",0,"70");
INSERT INTO TipoBilhete (id,nome,data_inicio,data_fim,acampamento,custo) VALUES (4,"Diario","10/07/2019","10/07/2019",1,"90");
INSERT INTO TipoBilhete (id,nome,data_inicio,data_fim,acampamento,custo) VALUES (5,"Diario","11/07/2019","11/07/2019",0,"70");
INSERT INTO TipoBilhete (id,nome,data_inicio,data_fim,acampamento,custo) VALUES (6,"Diario","11/07/2019","11/07/2019",1,"90");
INSERT INTO TipoBilhete (id,nome,data_inicio,data_fim,acampamento,custo) VALUES (7,"Pass","09/07/2019","11/07/2019",0,"100");
INSERT INTO TipoBilhete (id,nome,data_inicio,data_fim,acampamento,custo) VALUES (8,"Pass","09/07/2019","11/07/2019",1,"110");
INSERT INTO TipoBilhete (id,nome,data_inicio,data_fim,acampamento,custo) VALUES (9,"VIP","09/07/2019","11/07/2019",1,"250");

-- ZONA
INSERT INTO Zona (codigo,custo_m2,area) VALUES (1,3312,374);
INSERT INTO Zona (codigo,custo_m2,area) VALUES (2,3593,493);
INSERT INTO Zona (codigo,custo_m2,area) VALUES (3,4392,375);
INSERT INTO Zona (codigo,custo_m2,area) VALUES (4,3297,242);
INSERT INTO Zona (codigo,custo_m2,area) VALUES (5,4054,163);
INSERT INTO Zona (codigo,custo_m2,area) VALUES (6,4758,269);

PRAGMA foreign_keys = OFF;
